import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import LoadingLayout from "@/layouts/LoadingLayout";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import ReduxProvider from "@/layouts/ReduxProvider";
import Providers from "@/layouts/RTKProvider";
import Provider from "@/hocs/provider";
import { SkeletonTheme } from "react-loading-skeleton";
import PushMessageListener from "@/components/PushMessageListener";

export const metadata: Metadata = {
  title: "HR Portal",
  description: "Generated by create next app",
};

// const urbanist = Urbanist({
//   subsets: ["latin"],
//   // variable: "--font-urbanist",
//   weight: ["400", "500", "600", "700", "800"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastContainer
          position="bottom-right"
          limit={4}
          stacked
          closeOnClick
          toastClassName="text-sm sm:text-base rounded-lg shadow-md"
        />
        <Provider>
          <Providers>
            <>
              <ReduxProvider>
                <PushMessageListener />
                <SkeletonTheme
                  baseColor="#e4ecaa"
                  highlightColor="#fff"
                  borderRadius={"10px"}
                >
                  <LoadingLayout>{children}</LoadingLayout>
                </SkeletonTheme>
              </ReduxProvider>
            </>
          </Providers>
        </Provider>
      </body>
    </html>
  );
}
